-- MySQL Script generated by MySQL Workbench
-- jue 07 nov 2019 12:52:30 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `dni` VARCHAR(9) NOT NULL,
  `productividad` INT NOT NULL,
  `histórico_puesto` VARCHAR(64) NOT NULL,
  `gestiones_cliente_plus` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_plus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_plus` (
  `dni` VARCHAR(9) NOT NULL,
  `volumen_compras_mensual` INT NOT NULL,
  `n_pedidos` INT NOT NULL,
  `bonificación` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `cod_vivero` INT NOT NULL,
  PRIMARY KEY (`cod_vivero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `cod_zona` INT NOT NULL,
  `productividad` INT NOT NULL,
  `cod_vivero` INT NOT NULL,
  PRIMARY KEY (`cod_zona`, `cod_vivero`),
  INDEX `cod_vivero_idx` (`cod_vivero` ASC),
  CONSTRAINT `cod_vivero`
    FOREIGN KEY (`cod_vivero`)
    REFERENCES `mydb`.`Vivero` (`cod_vivero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona_Producto` (
  `cantidad` INT NOT NULL,
  `idP` INT NOT NULL,
  `cod_zona` INT NOT NULL,
  `cod_vivero` INT NOT NULL,
  INDEX `cod_zona_idx` (`cod_zona` ASC),
  PRIMARY KEY (`idP`, `cod_zona`, `cod_vivero`),
  INDEX `cod_vivero_idx` (`cod_vivero` ASC),
  CONSTRAINT `cod_zona`
    FOREIGN KEY (`cod_zona`)
    REFERENCES `mydb`.`Zona` (`cod_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`idP`)
    REFERENCES `mydb`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_vivero`
    FOREIGN KEY (`cod_vivero`)
    REFERENCES `mydb`.`Zona` (`cod_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado_Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado_Zona` (
  `fecha_ini` DATE NOT NULL,
  `dniE` VARCHAR(45) NOT NULL,
  `cod_zona` INT NOT NULL,
  `cod_vivero` INT NOT NULL,
  PRIMARY KEY (`fecha_ini`, `dniE`, `cod_vivero`, `cod_zona`),
  INDEX `cod_vivero_idx` (`cod_vivero` ASC),
  INDEX `cod_zona_idx` (`cod_zona` ASC),
  INDEX `dni_idx` (`dniE` ASC),
  CONSTRAINT `dni`
    FOREIGN KEY (`dniE`)
    REFERENCES `mydb`.`Empleado` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_zona`
    FOREIGN KEY (`cod_zona`)
    REFERENCES `mydb`.`Zona` (`cod_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_vivero`
    FOREIGN KEY (`cod_vivero`)
    REFERENCES `mydb`.`Zona` (`cod_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado_ClientePlus_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado_ClientePlus_Producto` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `precio` INT NOT NULL,
  `dniE` VARCHAR(45) NOT NULL,
  `dniCP` VARCHAR(45) NOT NULL,
  `idP` INT NOT NULL,
  PRIMARY KEY (`id`, `dniCP`, `dniE`, `idP`),
  INDEX `dniE_idx` (`dniE` ASC),
  INDEX `dniCP_idx` (`dniCP` ASC),
  INDEX `idP_idx` (`idP` ASC),
  CONSTRAINT `dniE`
    FOREIGN KEY (`dniE`)
    REFERENCES `mydb`.`Empleado` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `dniCP`
    FOREIGN KEY (`dniCP`)
    REFERENCES `mydb`.`Cliente_plus` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idP`
    FOREIGN KEY (`idP`)
    REFERENCES `mydb`.`Producto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
